name: WestLand
main: sk.westland.core.WestLand
depend: [ProtocolLib, Vault, AuthMe, Citizens, PlaceholderAPI, CMI, Residence, ShopGUIPlus, ForceResourcepacks, Votifier, Residence, LuckPerms]
load: POSTWORLD

author: XpresS
version: 1.0
api-version: 1.13

website: WestLand.eu
description: This plugin is developed for WestLand.eu